# Generated by Django 4.2.11 on 2026-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('WARNING', 'Warning')], default='PENDING', max_length=50)),
                ('severity', models.CharField(default='MEDIUM', max_length=20)),
                ('passed', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('expected_value', models.TextField(blank=True)),
                ('actual_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.PositiveIntegerField()),
                ('reference_number', models.CharField(max_length=100)),
                ('total_checks', models.PositiveIntegerField(default=0)),
                ('passed_checks', models.PositiveIntegerField(default=0)),
                ('failed_checks', models.PositiveIntegerField(default=0)),
                ('warning_checks', models.PositiveIntegerField(default=0)),
                ('overall_status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('WARNING', 'Warning')], default='PENDING', max_length=50)),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=100, unique=True)),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_description', models.TextField()),
                ('rule_type', models.CharField(choices=[('VALIDATION', 'Validation Rule'), ('BUSINESS_LOGIC', 'Business Logic Rule'), ('CALCULATION', 'Calculation Rule')], max_length=50)),
                ('category', models.CharField(choices=[('AGREEMENT', 'Agreement Rules'), ('INVOICE', 'Invoice Rules'), ('VENDOR', 'Vendor Rules')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('rule_config', models.JSONField(default=dict)),
                ('error_message', models.CharField(max_length=500)),
                ('execution_order', models.PositiveIntegerField(default=0)),
                ('is_blocking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compliance_rules',
                'ordering': ['execution_order', 'rule_code'],
            },
        ),
    ]
