# Generated by Django 4.2.11 on 2026-02-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=100, unique=True)),
                ('agreement_type', models.CharField(choices=[('VENDOR', 'Vendor Agreement'), ('FREIGHT', 'Freight Agreement'), ('SERVICE', 'Service Agreement')], default='VENDOR', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50)),
                ('agreement_start_date', models.DateField()),
                ('agreement_end_date', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('estimated_annual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_terms', models.CharField(default='Net 30', max_length=100)),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('DISCREPANCY', 'Discrepancy Found'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('invoice_file', models.FileField(upload_to='invoices/')),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_code', models.CharField(max_length=100)),
                ('rate_name', models.CharField(max_length=255)),
                ('rate_type', models.CharField(choices=[('FLAT_RATE', 'Flat Rate'), ('PER_MILE', 'Per Mile'), ('PER_KG', 'Per Kilogram'), ('PER_LB', 'Per Pound')], default='FLAT_RATE', max_length=50)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('service_level', models.CharField(blank=True, max_length=100)),
                ('equipment_type', models.CharField(blank=True, max_length=100)),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('tolerance_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='agreements.agreement')),
            ],
            options={
                'db_table': 'rate_configurations',
                'ordering': ['rate_code'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_type', models.CharField(choices=[('RATE_MISMATCH', 'Rate Mismatch'), ('QUANTITY_MISMATCH', 'Quantity Mismatch'), ('CALCULATION_ERROR', 'Calculation Error'), ('TOLERANCE_EXCEEDED', 'Tolerance Exceeded')], max_length=50)),
                ('line_item_number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('expected_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('difference_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financial_impact', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='agreements.invoice')),
                ('rate_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreements.rateconfiguration')),
            ],
            options={
                'db_table': 'invoice_discrepancies',
                'ordering': ['-created_at'],
            },
        ),
    ]
